coverage:
  status:
    project:
      default:
        target: auto
comment:
  require_changes: true
flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
