[default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*codespell:ignore\\s*$"]

[default.extend-words]
selectin = 'selectin'
odf = 'odf'
splitted = 'splitted'
asend = 'asend'
typ = 'typ'

[files]
extend-exclude = [
    "docs/changelog.rst",
    "docs/release-notes/changelog.rst",
    "/docs/examples/sqla/us_state_lookup.json",
]
