from openapi.utils import PersonController, PetController

from starlite import Starlite
from starlite.openapi.typescript_converter.converter import (
    convert_openapi_to_typescript,
)


def test_openapi_to_typescript_converter() -> None:
    app = Starlite(route_handlers=[PersonController, PetController])
    result = convert_openapi_to_typescript(openapi_schema=app.openapi_schema)
    assert (
        result.write() == "export namespace API {\n"
        "\texport namespace BulkCreatePerson {\n"
        "\texport interface HeaderParameters {\n"
        "\tsecret: string;\n"
        "};\n"
        "\n"
        "\texport namespace Http201 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "}[];\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport type RequestBody = undefined;\n"
        "};\n"
        "\n"
        "\texport namespace BulkPartialUpdatePerson {\n"
        "\texport interface HeaderParameters {\n"
        "\tsecret: string;\n"
        "};\n"
        "\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "}[];\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport type RequestBody = undefined;\n"
        "};\n"
        "\n"
        "\texport namespace BulkUpdatePerson {\n"
        "\texport interface HeaderParameters {\n"
        "\tsecret: string;\n"
        "};\n"
        "\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "}[];\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport type RequestBody = undefined;\n"
        "};\n"
        "\n"
        "\texport namespace CreatePerson {\n"
        "\texport interface HeaderParameters {\n"
        "\tsecret: string;\n"
        "};\n"
        "\n"
        "\texport namespace Http201 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport type RequestBody = undefined;\n"
        "};\n"
        "\n"
        "\texport namespace DeletePerson {\n"
        "\texport namespace Http204 {\n"
        "\texport type ResponseBody = undefined;\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport interface PathParameters {\n"
        "\tperson_id: string;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace GetPersonById {\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport interface PathParameters {\n"
        "\tperson_id: string;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace GetPersonDataclass {\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "};\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace GetPersons {\n"
        "\texport interface CookieParameters {\n"
        "\tvalue: number;\n"
        "};\n"
        "\n"
        "\texport interface HeaderParameters {\n"
        "\tsecret: string;\n"
        "};\n"
        "\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "}[];\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport interface PathParameters {\n"
        "\tservice_id: number;\n"
        "};\n"
        "\n"
        "\texport interface QueryParameters {\n"
        "\tfrom_date?: null | number | string | string;\n"
        '\tgender?: "A" | "F" | "M" | "O" | ("A" | "F" | "M" | "O")[] | null;\n'
        "\tname?: null | string | string[];\n"
        "\tpage: number;\n"
        "\tpageSize: number;\n"
        "\tto_date?: null | number | string | string;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace GetPetsOrOwners {\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = ({\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "} | {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "})[];\n"
        "\n"
        "\texport interface ResponseHeaders {\n"
        '\t"x-my-tag"?: string;\n'
        "};\n"
        "};\n"
        "\n"
        "\texport namespace Http406 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace PartialUpdatePerson {\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport interface PathParameters {\n"
        "\tperson_id: string;\n"
        "};\n"
        "\n"
        "\texport type RequestBody = undefined;\n"
        "};\n"
        "\n"
        "\texport namespace Pets {\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace UpdatePerson {\n"
        "\texport namespace Http200 {\n"
        "\texport type ResponseBody = {\n"
        "\tcomplex: {\n"
        "\t\n"
        "};\n"
        "\tfirst_name: string;\n"
        "\tid: string;\n"
        "\tlast_name: string;\n"
        "\toptional?: string;\n"
        "\tpets?: {\n"
        "\tage: number;\n"
        "\tname: string;\n"
        '\tspecies?: "Cat" | "Dog" | "Monkey" | "Pig";\n'
        "}[];\n"
        "};\n"
        "};\n"
        "\n"
        "\texport namespace Http400 {\n"
        "\texport type ResponseBody = {\n"
        "\tdetail: string;\n"
        "\textra?: Record<string, unknown> | null | unknown[];\n"
        "\tstatus_code: number;\n"
        "};\n"
        "};\n"
        "\n"
        "\texport interface PathParameters {\n"
        "\tperson_id: string;\n"
        "};\n"
        "\n"
        "\texport type RequestBody = undefined;\n"
        "};\n"
        "};"
    )
